defmodule ContentForge.Repo.Migrations.CreateContentBriefs do
  use Ecto.Migration

  def change do
    # Content Brief - the living strategy document
    create table(:content_briefs, primary_key: false) do
      add :id, :binary_id, primary_key: true

      add :product_id, references(:products, type: :binary_id, on_delete: :delete_all),
        null: false

      add :version, :integer, null: false, default: 1
      add :content, :text, null: false
      add :snapshot_id, :binary_id
      add :competitor_intel_id, :binary_id

      add :performance_summary, :map
      add :model_used, :string

      timestamps type: :utc_datetime
    end

    create index(:content_briefs, [:product_id])
    create index(:content_briefs, [:product_id, :version], unique: true)

    # Brief Version History
    create table(:brief_versions, primary_key: false) do
      add :id, :binary_id, primary_key: true

      add :content_brief_id,
          references(:content_briefs, type: :binary_id, on_delete: :delete_all), null: false

      add :version, :integer, null: false
      add :content, :text, null: false

      add :performance_summary, :map
      add :rewrite_reason, :string

      timestamps type: :utc_datetime
    end

    create index(:brief_versions, [:content_brief_id])
    create index(:brief_versions, [:content_brief_id, :version])

    # Draft - content variants generated by OpenClaw
    create table(:drafts, primary_key: false) do
      add :id, :binary_id, primary_key: true

      add :product_id, references(:products, type: :binary_id, on_delete: :delete_all),
        null: false

      add :content_brief_id, references(:content_briefs, type: :binary_id, on_delete: :nilify_all)

      # Content details
      add :content, :text, null: false
      add :platform, :string, null: false
      # post, blog, video_script
      add :content_type, :string, null: false
      # educational, entertaining, problem_aware, social_proof, humor, etc.
      add :angle, :string

      # Generation metadata
      add :generating_model, :string, null: false
      add :raw_response, :text

      # Status tracking
      # draft, ranked, approved, rejected, published
      add :status, :string, null: false, default: "draft"
      add :repurposed_from_id, :binary_id

      # Image (for social posts)
      add :image_url, :string

      timestamps type: :utc_datetime
    end

    create index(:drafts, [:product_id])
    create index(:drafts, [:product_id, :status])
    create index(:drafts, [:content_brief_id])
    create index(:drafts, [:repurposed_from_id])

    # Draft Score - per-model scoring
    create table(:draft_scores, primary_key: false) do
      add :id, :binary_id, primary_key: true
      add :draft_id, references(:drafts, type: :binary_id, on_delete: :delete_all), null: false
      # claude, gemini, xai
      add :model_name, :string, null: false

      # Scores (0-10)
      add :accuracy_score, :float
      add :seo_score, :float
      # entertainment/education value
      add :eev_score, :float
      add :composite_score, :float

      # Critique
      add :critique, :text

      timestamps type: :utc_datetime
    end

    create index(:draft_scores, [:draft_id])
    create index(:draft_scores, [:model_name])
    create index(:draft_scores, [:draft_id, :model_name], unique: true)
  end
end
